version: '3'
services:
  database:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dontusethisinprod
  app:
    image: galbwe92/meep
    build: .
    command: flask run --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - database

volumes:
  db_volume:
